### ISSUE TITLE
yakat pmpileup: Fallen over error on indels

### ISSUE THREAD

**Issue by nathanhaigh** [rsuchecki/yakat#1] opened 2019-03-22 20:33 UTC
I have read mappings produced by 'minimap2' and pileups generated by SAMtools. When using `yakat pmpileup` i get the following error. It seems to be caused by indel processing.

```
2019-03-22 Fri 12:50:38 [yakat pmpileup]       [ERROR]    Fallen over: .,^-, [210.42 MB]
```

Pileup from SAMtool mpileup. Line chr1A 60 show the offending line.

```
chr1A   60      C       3       .,^-,   FFF     1       ,       F
chr1A   61      C       3       .,,     FFF     1       ,       F
chr1A   62      C       3       .,,     F:F     1       ,       F
chr1A   63      T       3       .,,     FFF     1       ,       F
chr1A   64      A       3       .,,     FFF     1       ,       F
chr1A   65      A       3       .$,,    FFF     1       ,       F
chr1A   66      A       2       ,,      FF      1       ,       F
chr1A   67      C       1       ,       F       1       ,       F
chr1A   68      C       2       ,,      :F      1       ,       F
chr1A   69      C       2       ,,      FF      1       ,       F
chr1A   70      T       2       ,,      FF      1       ,       F
chr1A   71      A       2       ,,      :F      1       ,       F
chr1A   72      A       2       ,,      :F      1       ,       F
chr1A   73      A       2       ,,      :F      1       ,       F
chr1A   74      C       2       ,,      F:      1       ,       F
chr1A   75      C       2       ,,      :F      1       ,       F
chr1A   76      C       2       ,,      :F      1       ,       F
chr1A   77      C       2       ,,      F:      1       ,       F
chr1A   78      T       2       ,,-1a   FF      1       ,-1a    F
chr1A   79      A       2       ,*      FF      1       *       F
chr1A   80      A       2       ,,      FF      1       ,       F
chr1A   81      A       2       ,,      FF      1       ,       F
chr1A   82      C       2       ,,      FF      1       ,       F
chr1A   83      C       2       ,,      :F      1       ,       F
chr1A   84      C       2       ,,      FF      1       ,       F
chr1A   85      T       2       ,,      FF      1       ,       F
chr1A   86      A       2       ,,      FF      1       ,       F
chr1A   87      A       1       ,       F       1       ,       :
chr1A   88      A       2       ,,      :F      1       ,       F
chr1A   89      C       2       ,$,     FF      1       ,       F
chr1A   90      C       1       ,       F       1       ,       F
chr1A   91      C       1       ,       F       1       ,$      F
chr1A   92      T       1       ,       F       0       *       *
chr1A   93      A       1       ,       F       0       *       *
chr1A   94      A       1       ,+2ac   F       0       *       *
```

**Comment by nathanhaigh** [comment] 2019-03-23 08:41
Almost certain this wasn't the line causing the error. The log showed at least 100k records read before throwing this error!

**Comment by rsuchecki** [comment] 2019-03-23 10:02
I will have a look but it likely is the line, if I remember correctly the reporting of lines read is done by the reading thread - so not the one which fell flat. 

So we have segment start `^` which is ignored as intended but the following char `-` is recognised as deletion start instead of being ignored as fragment's MAPQ 45-33=12 (?). If you wouldn't mind sharing a more juicy chunk of the pileup file it should be easier to make sure the potential fix is general enough.

**Comment by rsuchecki** [comment] 2019-03-23 10:32
GH automation a bit overzealous - needs some testing before closing

**Comment by nathanhaigh** [comment] 2019-03-23 11:47
Will test this...phoenix is crapping it at the moment so it might take some time to feedback sucess/failure.

**Closed as completed** 2021-05-11 01:46 UTC
